name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Build
        run: |
          dotnet publish -r win-x64 -c Release -p:PublishReadyToRun=true -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true -o build/win-x64 .
      - name: Zip
        working-directory: build
        run: |
          tar -czvf DatetimeChanger.zip win-x64
      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: DatetimeChanger.zip
          path: build/DatetimeChanger.zip   
  release:
    runs-on: ubuntu-latest
    needs: [windows]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: DatetimeChanger.zip
          path: build
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/DatetimeChanger.zip
          asset_name: DatetimeChanger.zip
          asset_content_type: application/zip
